name: r_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _r-mutex=1.0.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - bleach=3.3.0
  - bwidget=1.9.11
  - bzip2=1.0.8
  - ca-certificates=2021.1.19
  - cairo=1.14.12
  - certifi=2020.12.5
  - cffi=1.14.0
  - curl=7.67.0
  - cyrus-sasl=2.1.26
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.3.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-anaconda=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - glib=2.63.1
  - graphite2=1.3.14
  - gsl=2.4
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=1.8.8
  - icu=58.2
  - importlib-metadata=3.7.3
  - importlib_metadata=3.7.3
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jinja2=2.11.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - krb5=1.16.4
  - ld_impl_linux-64=2.33.1
  - libcurl=7.67.0
  - libdb=6.1.26
  - libedit=3.1.20210216
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libntlm=1.5
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - make=4.2.1
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.3.0
  - openjdk=8.0.152
  - openssl=1.1.1k
  - packaging=20.9
  - pandoc=2.12
  - pandocfilters=1.4.3
  - pango=1.42.4
  - parso=0.8.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - pixman=0.40.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.17
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.8.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - python=3.8.2
  - python-dateutil=2.8.1
  - pyzmq=20.0.0
  - qt=5.6.3
  - r-askpass=1.0
  - r-assertthat=0.2.1
  - r-backports=1.1.4
  - r-base=3.6.1
  - r-base64enc=0.1_3
  - r-bh=1.69.0_1
  - r-bit=1.1_14
  - r-bit64=0.9_7
  - r-bitops=1.0_6
  - r-blob=1.1.1
  - r-boot=1.3_20
  - r-broom=0.5.2
  - r-callr=3.2.0
  - r-caret=6.0_83
  - r-catools=1.17.1.2
  - r-cellranger=1.1.0
  - r-class=7.3_15
  - r-cli=1.1.0
  - r-clipr=0.6.0
  - r-cluster=2.0.8
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-config=0.3
  - r-crayon=1.3.4
  - r-curl=3.3
  - r-data.table=1.12.2
  - r-dbi=1.0.0
  - r-dbplyr=1.4.0
  - r-dichromat=2.0_0
  - r-digest=0.6.18
  - r-dplyr=0.8.0.1
  - r-ellipsis=0.1.0
  - r-essentials=3.6.0
  - r-evaluate=0.13
  - r-fansi=0.4.0
  - r-forcats=0.4.0
  - r-foreach=1.4.4
  - r-foreign=0.8_71
  - r-forge=0.2.0
  - r-formatr=1.6
  - r-fs=1.2.7
  - r-generics=0.0.2
  - r-ggplot2=3.1.1
  - r-glmnet=2.0_16
  - r-glue=1.3.1
  - r-gower=0.2.0
  - r-gtable=0.3.0
  - r-haven=2.1.0
  - r-hexbin=1.27.2
  - r-highr=0.8
  - r-hms=0.4.2
  - r-htmltools=0.3.6
  - r-htmlwidgets=1.3
  - r-httpuv=1.5.1
  - r-httr=1.4.0
  - r-ipred=0.9_8
  - r-irdisplay=0.7.0
  - r-irkernel=0.8.15
  - r-iterators=1.0.10
  - r-jsonlite=1.6
  - r-kernsmooth=2.23_15
  - r-knitr=1.22
  - r-labeling=0.3
  - r-later=0.8.0
  - r-lattice=0.20_38
  - r-lava=1.6.5
  - r-lazyeval=0.2.2
  - r-lubridate=1.7.4
  - r-magrittr=1.5
  - r-maps=3.3.0
  - r-markdown=0.9
  - r-mass=7.3_51.3
  - r-matrix=1.2_17
  - r-mgcv=1.8_28
  - r-mime=0.6
  - r-miniui=0.1.1.1
  - r-modelmetrics=1.2.2
  - r-modelr=0.1.4
  - r-mongolite=2.0.1
  - r-munsell=0.5.0
  - r-nlme=3.1_139
  - r-nnet=7.3_12
  - r-numderiv=2016.8_1
  - r-odbc=1.1.5
  - r-openssl=1.3
  - r-packrat=0.5.0
  - r-pbdzmq=0.3_3
  - r-pillar=1.3.1
  - r-pkgconfig=2.0.2
  - r-pki=0.1_5.1
  - r-plogr=0.2.0
  - r-plyr=1.8.4
  - r-prettyunits=1.0.2
  - r-processx=3.3.0
  - r-prodlim=2018.04.18
  - r-profvis=0.3.5
  - r-progress=1.2.0
  - r-promises=1.0.1
  - r-ps=1.3.0
  - r-purrr=0.3.2
  - r-quantmod=0.4_14
  - r-r2d3=0.2.3
  - r-r6=2.4.0
  - r-randomforest=4.6_14
  - r-rappdirs=0.3.1
  - r-rbokeh=0.6.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.1
  - r-rcpproll=0.3.0
  - r-rcurl=1.95_4.12
  - r-readr=1.3.1
  - r-readxl=1.3.1
  - r-recipes=0.1.5
  - r-recommended=3.6.0
  - r-rematch=1.0.1
  - r-repr=0.19.2
  - r-reprex=0.2.1
  - r-reshape2=1.4.3
  - r-rjava=0.9_11
  - r-rjdbc=0.2_7.1
  - r-rjsonio=1.3_1.1
  - r-rlang=0.3.4
  - r-rmarkdown=1.12
  - r-rpart=4.1_15
  - r-rprojroot=1.3_2
  - r-rsconnect=0.8.13
  - r-rstudioapi=0.10
  - r-rvest=0.3.3
  - r-scales=1.0.0
  - r-selectr=0.4_1
  - r-shiny=1.3.2
  - r-sourcetools=0.1.7
  - r-sparklyr=1.0.0
  - r-spatial=7.3_11
  - r-squarem=2017.10_1
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=2.44_1.1
  - r-sys=3.2
  - r-tibble=2.1.1
  - r-tidyr=0.8.3
  - r-tidyselect=0.2.5
  - r-tidyverse=1.2.1
  - r-timedate=3043.102
  - r-tinytex=0.12
  - r-ttr=0.23_4
  - r-utf8=1.1.4
  - r-uuid=0.1_2
  - r-viridislite=0.3.0
  - r-whisker=0.3_2
  - r-withr=2.1.2
  - r-xfun=0.6
  - r-xml2=1.2.0
  - r-xtable=1.8_4
  - r-xts=0.11_2
  - r-yaml=2.2.0
  - r-zoo=1.8_6
  - readline=7.0
  - rstudio=1.1.456
  - send2trash=1.5.0
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.9.4
  - testpath=0.4.4
  - tk=8.6.10
  - tktable=2.10
  - tornado=6.1
  - traitlets=5.0.5
  - unixodbc=2.3.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
