channels:
- conda-forge
- bioconda
- defaults



dependencies:
## general
#- python=3.8
- r-base>=4.1.0
- git=2.30.2
- pip=21.0.1

## python packages
- bokeh=2.3.3
- colorcet=2.0.6
- dabl=0.2.2
- glpk=5.0
- graphviz=2.47.3
- gseapy=0.10.4
- hdbscan=0.8.27
- holoviews=1.14.4
- jupyter_contrib_nbextensions=0.5.1
- jupyter_core=4.7.1
- jupyter=1.0.0
- keras #=2.3.1
- leidenalg=0.8.3
- matplotlib=3.4.2
- mpmath=1.2.1
- nb_conda_kernels=2.3.1
- nbconvert #=5.6.1
- numba=0.53.1
- numpy=1.20.2
- pandas-profiling=2.11.0
- pandas=1.2.3
- pip:
    - combat==0.2.1
    - cobra==0.22.1
    - datashader==0.12.1
    - pca==1.3.0
    - snfpy==0.2.2
- pycairo=1.19.1
- python-graphviz=0.16
- python-igraph=0.8.3
- rpy2 #=3.1.0
- scikit-learn=0.24.1
- scipy=1.6.2
- seaborn=0.11.1
- statsmodels=0.12.2
- tensorflow=2.4.1
- umap-learn=0.5.1

## others
- ruamel_yaml